### from 菜鸟教程（runoob）

#### 数组

In [3]:
# 一维数组

arr = [1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [4]:
arr = [1, "Julia", 3.7, π]

4-element Vector{Any}:
 1
  "Julia"
 3.7
 π = 3.1415926535897...

In [5]:
# 也可以强制指定类型
arr = Int64[1, 2, 3, 4, 5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [6]:
arr = String["Julia", "Python", "C++"]

3-element Vector{String}:
 "Julia"
 "Python"
 "C++"

In [7]:
# 创建一个空数组
arr = Int64[]

Int64[]

In [8]:
arr = String[]

String[]

In [9]:
arr = String["JUlia", "Python", "C++", "Ruby", "Kotlin", "Mojo", "Go", "Rust", "V", "Zig"]
arr[end]

"Zig"

In [15]:
# 指定数组的类型及维度
array = Array{Int64}(undef, 3) # 表示一维数组，数组有 3 个元素

3-element Vector{Int64}:
 2239399878472
 2239400256936
             0

In [16]:
array = Array{Int64}(undef, 3, 3, 3)

3×3×3 Array{Int64, 3}:
[:, :, 1] =
 0  3  6
 1  4  7
 2  4  8

[:, :, 2] =
  9   3   3
 10  13  16
 11  14  17

[:, :, 3] =
 17  21  24
 19  22  25
 19  23  26

#### 二维数组

>  Julia 只认可列向量，而不认可所谓的行向量

In [17]:
[1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [18]:
[1;; 2;; 3;; 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [19]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [20]:
[1:2 3:4]

2×2 Matrix{Int64}:
 1  3
 2  4

In [21]:
[[1,2] [3,4] [5,6]]

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [22]:
[[1;2] [3;4] [5;6]]

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [24]:
[[1 2]; [3 4]; [5 6]]

3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

In [25]:
# 使用范围函数来创建数组
# 方式一：省略号
[1:10...]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [26]:
# 方式二：使用collect函数
# 语法：collect(start:step:stop)

collect(1:2:13)#值为 1，步长为 2，结束值为 13：

7-element Vector{Int64}:
  1
  3
  5
  7
  9
 11
 13

In [27]:
# collect() 函数也可以指定类型，语法格式如下：
# collect(element_type, start:step:stop)

collect(Float64, 1:2:5)# 生成一个浮点数数组

3-element Vector{Float64}:
 1.0
 3.0
 5.0

In [10]:
# range 函数
# 语法格式：range(start, stop, length) 
# range(start, stop; length, step) 
# range(start; length, stop, step) 
# range(;start, length, stop, step)
range(1, length=100)
range(1, stop=100)
range(1, step=5, length=100)
range(1, step=5, stop=100)
range(1, 10, length=101)
range(1, 100, step=5)
range(stop=10, length=5)
range(stop=10, step=1, length=5)
range(start=1, step=1, stop=10)

1:1:10

In [11]:
range(1, 3.5, step=2)

1.0:2.0:3.0

In [12]:
# 使用 range() 和 collect() 创建数组：
collect(range(1, 10))

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [13]:
collect(range(1, length=15, stop=150))

15-element Vector{Float64}:
   1.0
  11.642857142857142
  22.285714285714285
  32.92857142857143
  43.57142857142857
  54.214285714285715
  64.85714285714286
  75.5
  86.14285714285714
  96.78571428571429
 107.42857142857143
 118.07142857142857
 128.71428571428572
 139.35714285714286
 150.0

In [14]:
# 使用推导式和生成器创建数组
# 数组推导式语法格式如下：
# A = [ F(x,y,...) for x=rx, y=ry, ... ]


[x^2 for x in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [15]:
# 创建二维数组
[n*m for n in 1:3, m in 1:4]

3×4 Matrix{Int64}:
 1  2  3   4
 2  4  6   8
 3  6  9  12

In [16]:
# 也可以在没有方括号的情况下编写（数组）推导，从而产生称为生成器的对象。

# 以下实例创建一个数组：
collect(n^2 for n in 1:10)

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [17]:
# 在不分配内存的情况下对一个序列进行求和
sum(1/n^2 for n in 1:100)

1.6349839001848923

In [18]:
# zeros() 创建数组实例，元素初始值 都是 0:

zeros(Int, 3, 4)

3×4 Matrix{Int64}:
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [2]:
zeros(Float64, (3, 4))

3×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [1]:
zeros((2, 3))

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0